### ISSUE TITLE
Syntax error on login command

### ISSUE THREAD

**Issue by papabert** [wpietri/sucks#58]
Hello,

I installed sucks on my RPI today (v0.9.3) with Python 3.4.2 but I get the following error when I run the "sucks login" command:

`Traceback (most recent call last):`
`  File "/usr/local/bin/sucks", line 7, in <module>`
`    from sucks.cli import cli`
`  File "/usr/local/lib/python2.7/dist-packages/sucks/__init__.py", line 360`
`    def is_charging(self) -> bool:`
`                          ^`
`SyntaxError: invalid syntax`

If you can help me, I would really like to drive my ecovacs. And sorry, but I'm a python beginner...

Thanks !

**Comment by papabert** [comment]
I found the problem myself...
I have two versions of Python installed on my RPI (2 and 3).
I forced the installation of sucks with the command:
`sudo python3 -m pip install sucks`
It's ok now.
Sorry for the inconvenience.
