### ISSUE TITLE
Unable to start sucks or setup login

### ISSUE THREAD

**Issue by hakarune** [wpietri/sucks#69]
Followed setup guide on the Git page, but it just gives me errors. pip installed sucks just fine, but trying to setup login or issuing commands fails. Tried several ways to use this and nothing works. How do you actually use this?

> Operating System: Debian GNU/Linux 9 (stretch)
>             Kernel: Linux 4.18.0-0.bpo.3-amd64
>       Architecture: x86-64

**root@omvnas:~# % sucks login**
`bash: fg: %: no such job`
**root@omvnas:~# sucks login**
```Traceback (most recent call last):
  File "/usr/local/bin/sucks", line 7, in <module>
    from sucks.cli import cli
  File "/usr/local/lib/python2.7/dist-packages/sucks/__init__.py", line 360
    def is_charging(self) -> bool:
                          ^
SyntaxError: invalid syntax
```
**root@omvnas:~# % sucks clean 10**
`bash: fg: %: no such job`

Ran from the bin folder where it's located even
**root@omvnas:/bin# sucks login**
```
Traceback (most recent call last):
  File "/usr/local/bin/sucks", line 7, in <module>
    from sucks.cli import cli
  File "/usr/local/lib/python2.7/dist-packages/sucks/__init__.py", line 360
    def is_charging(self) -> bool:
                          ^
SyntaxError: invalid syntax
```

Tried running via python and still nothing

 **>>> sucks login**

```
File "<stdin>", line 1
    sucks login
              ^
SyntaxError: invalid syntax
```

**Comment by hakarune** [comment]
Found the issue.

Your git is out of date. installing pip3 then installing sucks with pip3 I can not get to login setup
