### ISSUE TITLE
Deebot 600 Series - "performing clean command" then does nothing

### ISSUE THREAD

**Issue by winell28** [wpietri/sucks#83]
Trying to get sucks to run on my Raspberry Pi with my Deebot 600 series.

Keep getting the following:

```
pi@raspberrypi:~ $ sucks clean 1
sleekxmppfs.basexmpp WARNING  fulljid property deprecated. Use boundjid.resource
performing clean command
Traceback (most recent call last):
  File 
"/usr/local/bin/sucks", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1164, in invoke
    return _process_result(rv)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1102, in _process_result
    **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sucks/cli.py", line 219, in run
    vacbot.run(action.vac_command)
  File "/usr/local/lib/python3.6/site-packages/sucks/__init__.py", line 416, in run
    self.send_command(action.to_xml())
  File "/usr/local/lib/python3.6/site-packages/sucks/__init__.py", line 413, in send_command
    self.xmpp.send_command(xml, self._vacuum_address())
  File "/usr/local/lib/python3.6/site-packages/sucks/__init__.py", line 482, in send_command
    c.send()
  File "/usr/local/lib/python3.6/site-packages/sleekxmppfs/stanza/iq.py", line 235, in send
    raise IqError(result)
sleekxmppfs.exceptions.IqError: <iq type="error" to="########@ecouser.net/########" from="########@dl8fht.ecorobot.net/atom" id="########"><error type="wait" code="404"><recipient-unavailable xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" /></error></iq>
```

Then nothing happens.

Any ideas would be greatly appreciated!

**Comment by wpietri** [comment]
Sorry, but that is not a supported model.
